#!/usr/bin/env bash
# Configure my domain zone:

get_record_info() {
  local domain="$1"
  local subdomain="$2"

  if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record_type=$(dig "$sub.$domain" +short)
    destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $NF}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
}

# Parse command-line arguments
if [[ $# -eq 1 ]]; then
  get_record_info "$1"
elif [[ $# -eq 2 ]]; then
  get_record_info "$1" "$2"
else
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi
