#!/usr/bin/env bash
# shellcheck disable=SC2154
#configures a new Ubuntu machine nginx
# Update the system packages
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Configure Nginx to add custom response header
sudo bash -c 'echo -e "add_header X-Served-By \$hostname;" > /etc/nginx/conf.d/custom-header.conf'

# Restart Nginx
sudo systemctl restart nginx
